language: python
python: 3.6
install: skip
jobs:
  include:
  - stage: deploy to digital ocean
    install: skip
    script: skip
    before_deploy:
    - openssl aes-256-cbc -K $encrypted_8a486bdb9bb9_key -iv $encrypted_8a486bdb9bb9_iv
      -in travis_id_rsa.enc -out ./travis_id_rsa -d
    - eval "$(ssh-agent -s)"
    - chmod 600 ./travis_id_rsa
    - ssh-add ./travis_id_rsa
    deploy:
      provider: script
      skip_cleanup: true
      script: ssh -o "StrictHostKeyChecking no" root@play.term.ninja < ./deploy.sh
      on:
        branch: master


