language: node_js
node_js:
  - "10.13.0"
install: skip
jobs:
  include:
  - stage: deploy api and games to digital ocean
    install: skip
    script: skip
    before_deploy:
    - openssl aes-256-cbc -K $encrypted_8a486bdb9bb9_key -iv $encrypted_8a486bdb9bb9_iv
      -in travis_id_rsa.enc -out ./travis_id_rsa -d
    - eval "$(ssh-agent -s)"
    - chmod 600 ./travis_id_rsa
    - ssh-add ./travis_id_rsa
    deploy:
      provider: script
      skip_cleanup: true
      script: ssh -o "StrictHostKeyChecking no" root@play.term.ninja < ./deploy_api.sh
      on:
        branch: master

  - stage: deploy frontend to zeit
    install: skip
    script: skip
    before_deploy:
      - npm i -g now
    deploy:
      provider: script
      skip_cleanup: true
      script: deploy_frontend.sh
      on:
        branch: master