language: node_js

node_js:
  - "10.13.0"

sudo: required

services:
  - docker

stages:
  - build base
  - build
  - deploy

install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

jobs:
  include:
  - stage: build base
    name: build and push base image
    script:
      - docker-compose build base
      - docker-compose push base
  
  - stage: build
    name: build and push api image
    script:
      - docker-compose build api
      - docker-compose push api
  
  - stage: build
    name: build and push games image
    script:
      - docker-compose build games
      - docker-compose push games

  - stage: deploy
    name: deploy backend to digital ocean
    script:
      - eval "$(ssh-agent -s)"
      - openssl aes-256-cbc -K $encrypted_8a486bdb9bb9_key -iv $encrypted_8a486bdb9bb9_iv
        -in travis_id_rsa.enc -out ./travis_id_rsa -d
      - chmod 600 ./travis_id_rsa
      - ssh-add ./travis_id_rsa
      - ssh -o "StrictHostKeyChecking no" root@play.term.ninja 'cd termninja-docker; git pull; ./redeploy.sh'

  - stage: deploy
    name: deploy frontend to zeit
    script:
      - npm i -g now
      - cp ./client.sh ./frontend/public/client
      - npm install
      - now -t $now_deploy_token --target production ./frontend/
