version: '3'

services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - config.env
      - config.dev.env

  base:
    build:
      context: ./base
      args:
        editable: sure
    depends_on:
      - postgres
    
  api:
    build: ./api
    ports:
      - 8080:3000
    depends_on:
      - postgres
      - base
    env_file:
      - config.env
      - config.dev.env
    volumes:
      - ./api/:/api/
      - ./base/termninja_db/:/base/termninja_db/

  games:
    build: ./games
    ports:
      - 3333:3000
    command: --debug
    depends_on:
      - postgres
      - api
      - base
    env_file:
      - config.env
      - config.dev.env
    volumes:
      - ./games/:/app/
      - ./base/termninja_db/:/base/termninja_db/
  