version: '3'

services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - config.env

  core:
    build:
      context: ./core
      args:
        editable: sure
    depends_on:
      - postgres
    
  api:
    build: ./api
    ports:
      - 80:3000
    depends_on:
      - postgres
    env_file:
      - config.env
      - config.dev.env
    volumes:
      - ./api/:/api/
      - ./core/termninja/:/core/termninja/

  subnet-racer:
    build: ./subnet-racer
    command: -p 3001 -a
    ports:
      - 3001:3001
    depends_on:
      - core
      - postgres
    env_file:
      - config.env
      - config.dev.env
    volumes:
        - ./core/termninja/:/core/termninja/
        - ./subnet-racer/:/app/
    
  snake:
    build: ./snake
    command: -p 3002 -a
    ports:
      - 3002:3002
    depends_on:
      - core
      - postgres
    env_file:
      - config.env
      - config.dev.env
    volumes:
      - ./core/termninja/:/core/termninja/
      - ./snake/:/app/
    
    
  tic-tac-toe:
    build: ./tic-tac-toe
    command: -p 3003 -a
    ports:
      - 3003:3003
    depends_on:
      - core
      - postgres
    env_file:
      - config.env
      - config.dev.env
    volumes:
      - ./core/termninja/:/core/termninja/
      - ./tic-tac-toe/:/app/
