version: "3"

services:
  base:
    build:
      args:
        editable: 1

  api:
    volumes:
      - ./api/:/api/
      - ./base/termninja_db/:/base/termninja_db/
    environment:
      - DEBUG=1

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/:/app/
    environment:
      - DEBUG=1

  games:
    command: --debug
    volumes:
      - ./games/:/app/
      - ./base/termninja_db/:/base/termninja_db/
    environment:
      - DEBUG=1
