version: '3'

services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - config.env

  base:
    image: jhackshaw/termninja-base
    build:
      context: ./base
      args:
        editable: ${TERMNINJA_DEVELOP}
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - 80:3000
    depends_on:
      - api
    volumes:
      - ./frontend/:/app/
    env_file:
      - config.env
    network_mode: host

  api:
    image: jhackshaw/termninja-api
    build: ./api
    ports:
      - 8080:3000
    depends_on:
      - postgres
    volumes:
      - ./api/:/api/
      - ./base/termninja_db/:/base/termninja_db/
    env_file:
      - config.env

  games:
    image: jhackshaw/termninja-games
    build: ./games
    ports:
      - 3333:3000
    command: --debug
    depends_on:
      - postgres
      - api
    volumes:
      - ./games/:/app/
      - ./base/termninja_db/:/base/termninja_db/
    env_file:
      - config.env
  