version: "3"

services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - ./config.env

  redis:
    image: redis:5.0.5-alpine
    restart: always
    env_file:
      - ./config.env

  base:
    build:
      context: ./base
      args:
        editable: 1
    depends_on:
      - postgres

  migrate:
    build: ./api
    command: alembic upgrade head
    depends_on:
      - base
      - postgres
    env_file:
      - ./config.env

  api:
    build: ./api
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - base
      - migrate
    env_file:
      - ./config.env

  frontend:
    build: ./frontend
    ports:
      - 80:3000
    depends_on:
      - api
    env_file:
      - ./config.env

  games:
    build: ./games
    ports:
      - 3333:3000
    depends_on:
      - postgres
      - api
      - base
    env_file:
      - ./config.env
