version: '3'

services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - config.env
    volumes:
      - /mnt/volume_nyc1_03/postgres_data:/var/lib/postgresql/data

  base:
    image: jhackshaw/termninja-base
    build:
      context: ./base
    depends_on:
      - postgres
    
  api:
    image: jhackshaw/termninja-api
    build: ./api
    ports:
      - 443:3000
    depends_on:
      - postgres
      - base
    env_file:
      - config.env
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

  games:
    image: jhackshaw/termninja-games
    build: ./games
    ports:
      - 3333:3000
    depends_on:
      - postgres
      - api
      - base
    env_file:
      - config.env
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
